language: python
sudo: required
notifications:
  email: false
python:
  - "3.6"
  - "nightly"

install:
  - pip install nose
script:
  - nosetests -vd -w matching/Python testUtils.py
  - nosetests -vd -w closest-points/src testParse.py
  - nosetests -vd -w gorilla/src test.py
  - nosetests -vd -w flow/src test.py
  - nosetests -vd -w flow/src test_parser.py
  - nosetests -vd -w flow/src test_path.py
<<<<<<< f2d98bd27be05fc1cc1f9c36b28ebb091349bc55
  - nosetests -vd -w flow/src test_cut.py
=======
>>>>>>> Fixed get_valid_path and added test, tabs incoming?!
